[package]
name = "MovementBaskets"
version = "2.0.0"
authors = []

[addresses]
cresca = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.8"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.8"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.8"
subdir = "aptos-move/framework/move-stdlib"

[dev-addresses]
cresca = "0xcafe"
